name: Build Miatoll Kernel

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout Source
    uses: actions/checkout@v4

  - name: Install Dependencies
    run: |
      sudo apt update
      sudo apt install -y \
      bc \
      bison \
      build-essential \
      ccache \
      curl \
      flex \
      git \
      libssl-dev \
      python3

  - name: Clone Proton Clang
    run: |
      git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

  - name: Configure Kernel
    run: |
      export ARCH=arm64
      export SUBARCH=arm64
      export PATH=$PWD/clang/bin:$PATH

      make O=out \
      ARCH=arm64 \
      vendor/xiaomi/miatoll_defconfig

  - name: Build Kernel
    run: |
      export ARCH=arm64
      export SUBARCH=arm64
      export PATH=$PWD/clang/bin:$PATH

      make -j$(nproc) \
      O=out \
      ARCH=arm64 \
      CC=clang \
      LLVM=1 \
      LLVM_IAS=1

  - name: Upload Output
    uses: actions/upload-artifact@v4
    with:
      name: kernel-out
      path: out/
